# Generated by Django 5.1.15 on 2026-06-29 08:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HUNumberingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        default="HU", max_length=10, verbose_name="prefiks"
                    ),
                ),
                (
                    "next_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="następny numer"
                    ),
                ),
                (
                    "padding",
                    models.PositiveSmallIntegerField(
                        default=8, verbose_name="liczba cyfr"
                    ),
                ),
            ],
            options={
                "verbose_name": "konfiguracja numeracji HU",
                "verbose_name_plural": "konfiguracja numeracji HU",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=40, unique=True, verbose_name="kod"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PICKING", "Picking"), ("ZAPAS", "Zapas")],
                        default="ZAPAS",
                        max_length=10,
                        verbose_name="typ",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Informacyjnie — system nie blokuje przepełnienia.",
                        verbose_name="pojemność (liczba HU)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="utworzono"
                    ),
                ),
            ],
            options={
                "verbose_name": "lokalizacja",
                "verbose_name_plural": "lokalizacje",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="kod"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=50, verbose_name="nazwa"),
                ),
            ],
            options={
                "verbose_name": "jednostka miary",
                "verbose_name_plural": "jednostki miary",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="HandlingUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="numer HU"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="ilość"),
                ),
                (
                    "lot",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="partia / LOT"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="data ważności"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DO_ULOZENIA", "Do ułożenia"),
                            ("ZMAGAZYNOWANY", "Zmagazynowany"),
                            ("PUSTY", "Pusty"),
                        ],
                        default="DO_ULOZENIA",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "delivery_ref",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="numer dostawy"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="przyjęto"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="przyjął",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handling_units",
                        to="warehouse.location",
                        verbose_name="lokalizacja",
                    ),
                ),
            ],
            options={
                "verbose_name": "HU (paleta)",
                "verbose_name_plural": "HU (palety)",
                "ordering": ["-created_at", "number"],
            },
        ),
        migrations.CreateModel(
            name="IssueDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="numer dokumentu"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="referencja"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OTWARTY", "Otwarty"),
                            ("ZREALIZOWANY", "Zrealizowany"),
                        ],
                        default="OTWARTY",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="utworzono"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="zrealizowano"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utworzył",
                    ),
                ),
            ],
            options={
                "verbose_name": "dokument wydania",
                "verbose_name_plural": "dokumenty wydania",
                "ordering": ["-created_at", "number"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.CharField(max_length=40, unique=True, verbose_name="indeks"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nazwa")),
                (
                    "max_per_pallet",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Sztywny limit ilości na jednej palecie (opcjonalny).",
                        null=True,
                        verbose_name="maks. ilość na palecie",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="utworzono"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utworzył",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="warehouse.unit",
                        verbose_name="jednostka",
                    ),
                ),
            ],
            options={
                "verbose_name": "materiał",
                "verbose_name_plural": "materiały",
                "ordering": ["index"],
            },
        ),
        migrations.CreateModel(
            name="IssueLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_qty",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="ilość żądana",
                    ),
                ),
                (
                    "picked_qty",
                    models.PositiveIntegerField(default=0, verbose_name="ilość wydana"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="warehouse.issuedocument",
                        verbose_name="dokument",
                    ),
                ),
                (
                    "specific_hu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="warehouse.handlingunit",
                        verbose_name="konkretny HU",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="warehouse.material",
                        verbose_name="materiał",
                    ),
                ),
            ],
            options={
                "verbose_name": "pozycja wydania",
                "verbose_name_plural": "pozycje wydania",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="handlingunit",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="handling_units",
                to="warehouse.material",
                verbose_name="materiał",
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("OPERATOR", "Operator"),
                            ("VIEWER", "Podgląd"),
                        ],
                        default="VIEWER",
                        max_length=10,
                        verbose_name="rola",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="użytkownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil użytkownika",
                "verbose_name_plural": "profile użytkowników",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PRZYJECIE", "Przyjęcie"),
                            ("ALOKACJA", "Alokacja"),
                            ("PRZESUNIECIE", "Przesunięcie"),
                            ("KOREKTA", "Korekta"),
                            ("WYDANIE", "Wydanie"),
                        ],
                        max_length=15,
                        verbose_name="typ",
                    ),
                ),
                (
                    "quantity_delta",
                    models.IntegerField(
                        help_text="Dodatnia dla przyjęcia, ujemna dla wydania, 0 dla przesunięcia.",
                        verbose_name="zmiana ilości",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="uwagi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="kiedy"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="kto",
                    ),
                ),
                (
                    "handling_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="warehouse.handlingunit",
                        verbose_name="HU",
                    ),
                ),
                (
                    "issue_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="warehouse.issuedocument",
                        verbose_name="dokument wydania",
                    ),
                ),
                (
                    "location_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="warehouse.location",
                        verbose_name="z lokalizacji",
                    ),
                ),
                (
                    "location_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="warehouse.location",
                        verbose_name="do lokalizacji",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="warehouse.material",
                        verbose_name="materiał",
                    ),
                ),
            ],
            options={
                "verbose_name": "ruch magazynowy",
                "verbose_name_plural": "ruchy magazynowe",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
