# Generated by Django 5.1.15 on 2026-06-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_seed_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="type",
            field=models.CharField(
                choices=[
                    ("PRZYJECIE", "Przyjęcie"),
                    ("ALOKACJA", "Alokacja"),
                    ("PRZESUNIECIE", "Przesunięcie"),
                    ("KOREKTA", "Korekta"),
                    ("WYDANIE", "Wydanie"),
                    ("PRZEPAKOWANIE", "Przepakowanie"),
                ],
                max_length=15,
                verbose_name="typ",
            ),
        ),
    ]
