# Generated by Django 5.1.15 on 2026-06-29 18:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0003_alter_stockmovement_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USZKODZENIE", "Uszkodzenie"),
                    ("STRATA", "Strata / ubytek"),
                    ("NADWYZKA", "Nadwyżka"),
                    ("POMYLKA", "Pomyłka ewidencji"),
                    ("SPIS", "Spis z natury"),
                    ("INNE", "Inne"),
                ],
                max_length=12,
                verbose_name="powód korekty",
            ),
        ),
        migrations.CreateModel(
            name="StocktakeSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="numer arkusza"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OTWARTY", "Otwarty"), ("ZAMKNIETY", "Zamknięty")],
                        default="OTWARTY",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="utworzono"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="zamknięto"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utworzył",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Puste = cały magazyn.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="warehouse.location",
                        verbose_name="lokalizacja (zakres)",
                    ),
                ),
            ],
            options={
                "verbose_name": "arkusz spisu",
                "verbose_name_plural": "arkusze spisu",
                "ordering": ["-created_at", "number"],
            },
        ),
        migrations.CreateModel(
            name="StocktakeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_code",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="lokalizacja"
                    ),
                ),
                ("expected_qty", models.IntegerField(verbose_name="stan ewidencyjny")),
                (
                    "counted_qty",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="policzono"
                    ),
                ),
                (
                    "handling_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="warehouse.handlingunit",
                        verbose_name="HU",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="warehouse.material",
                        verbose_name="materiał",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="warehouse.stocktakesheet",
                        verbose_name="arkusz",
                    ),
                ),
            ],
            options={
                "verbose_name": "pozycja spisu",
                "verbose_name_plural": "pozycje spisu",
                "ordering": ["location_code", "id"],
            },
        ),
    ]
