# Generated by Django 5.1.15 on 2026-06-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0004_stockmovement_reason_stocktakesheet_stocktakeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="handlingunit",
            name="delivery_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="termin dostawy"
            ),
        ),
    ]
