# Generated by Django 5.1.15 on 2026-06-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0005_handlingunit_delivery_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuedocument",
            name="carrier",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="przewoźnik"
            ),
        ),
        migrations.AddField(
            model_name="issuedocument",
            name="packed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="spakowano"),
        ),
        migrations.AddField(
            model_name="issuedocument",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="wysłano"),
        ),
        migrations.AddField(
            model_name="issuedocument",
            name="tracking_number",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="nr przesyłki"
            ),
        ),
        migrations.AlterField(
            model_name="issuedocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("OTWARTY", "Otwarty"),
                    ("ZREALIZOWANY", "Zrealizowany"),
                    ("SPAKOWANY", "Spakowany"),
                    ("WYSLANY", "Wysłany"),
                ],
                default="OTWARTY",
                max_length=15,
                verbose_name="status",
            ),
        ),
    ]
