# Generated by Django 5.1.15 on 2026-06-30 05:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0006_issuedocument_carrier_issuedocument_packed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(blank=True, max_length=150, verbose_name="login"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Logowanie"),
                            ("LOGOUT", "Wylogowanie"),
                            ("FAILED", "Nieudane logowanie"),
                        ],
                        max_length=10,
                        verbose_name="zdarzenie",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="adres IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="przeglądarka"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="kiedy"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="użytkownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "zdarzenie logowania",
                "verbose_name_plural": "dziennik logowań",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
