# Generated by Django 5.1.15 on 2026-06-30 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0007_loginevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="capacity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Maksymalna liczba HU. 0 = bez limitu. Alokacja pilnuje limitu.",
                verbose_name="pojemność (liczba HU)",
            ),
        ),
        migrations.AddIndex(
            model_name="handlingunit",
            index=models.Index(fields=["status"], name="warehouse_h_status_ac54cf_idx"),
        ),
        migrations.AddIndex(
            model_name="handlingunit",
            index=models.Index(
                fields=["material", "status"], name="warehouse_h_materia_8f39bc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="handlingunit",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="hu_quantity_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="material",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_per_pallet__isnull", True),
                    ("max_per_pallet__gte", 1),
                    _connector="OR",
                ),
                name="material_max_per_pallet_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktakeline",
            constraint=models.UniqueConstraint(
                fields=("sheet", "handling_unit"), name="uniq_stocktake_sheet_hu"
            ),
        ),
    ]
